CREATE TABLE IF NOT EXISTS `bors_images` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(255) NOT NULL DEFAULT '',
  `alt` varchar(255) NOT NULL DEFAULT '',
  `description` text NOT NULL,
  `parent_class_id` int(11) NOT NULL DEFAULT '0',
  `parent_object_id` int(11) NOT NULL DEFAULT '0',
  `sort_order` int(11) NOT NULL DEFAULT '0',
  `author_name` varchar(255) NOT NULL DEFAULT '',
  `image_type` varchar(32) NOT NULL DEFAULT '',
  `create_time` int(10) unsigned NOT NULL DEFAULT '0',
  `modify_time` int(10) unsigned NOT NULL DEFAULT '0',
  `full_file_name` varchar(255) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL,
  `full_url` varchar(255) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL,
  `relative_path` varchar(255) NOT NULL DEFAULT '',
  `file_name` varchar(255) NOT NULL DEFAULT '',
  `original_filename` varchar(255) NOT NULL DEFAULT '',
  `resolution_limit` int(10) unsigned NOT NULL DEFAULT '0',
  `width` int(10) unsigned NOT NULL DEFAULT '0',
  `height` int(10) unsigned NOT NULL DEFAULT '0',
  `size` int(10) unsigned NOT NULL DEFAULT '0',
  `extension` varchar(6) NOT NULL DEFAULT '',
  `mime_type` varchar(255) NOT NULL DEFAULT '',
  `created_from` varchar(255) DEFAULT NULL,
  `moderated` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `full_file_name` (`full_file_name`),
  UNIQUE KEY `full_url` (`full_url`),
  KEY `create_time` (`create_time`),
  KEY `modify_time` (`modify_time`),
  KEY `resolution_limit` (`resolution_limit`),
  KEY `parent_class_id` (`parent_class_id`,`parent_object_id`),
  KEY `order` (`sort_order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
