<?php

bors_url_submap(array(
	'/ => _main',
	'/action\?(\w+) => _action(1)',
	'/append/child\?object=([^&]*) => _append_child(1)',
	'/classes/(\w+)/? => _classes_edit(1)',
	'/classes/(\w+)/new/? => _classes_new(1)',
	'/cross_chtype\?.* => _cross_chtype',
	'/cross_unlink\?.* => _cross_unlink',
	'/delete/\?object=([^&]+).* => bors_tools_delete(1)',
	'/dev/chuser/(.+)$ => _dev_chuser(1)',
	'/edit/crosslinks/ => bors_admin_edit_crosslinks',
	'/edit/page\?object=([^&]+) => _edit_page(1)',
	'/edit-smart/\?object=([^&]+).* => _edit_smart(1)',
	'/edit-smart/ => _edit_smart',
	'/edit-var\?var=([^&]+).* => _edit_var(1)',
	'/links/ => _links_main',
	'/links/(\d+)\.html => _links_main(NULL,1)',
	'/links/search/ => _links_search',
	'/links/checklist/(\w+/\w+)/? => _links_checklist(NULL,1)',
	'/mark/delete/\?object=([^&]+).* => _mark_delete(1)',
	'/new\?class_name=(.+) => _edit_smart(1)',
	'/objects/? => _objects_main',
	'/objects/(\w+)/? => _objects_list(1)',
	'/objects\?class=(\w+) => _objects_list(1)',
	'/objects/edit\?class=(\w+)&id=(\w+) => _objects_edit(2,1)',
	'/objects/edit\?class=(\w+) => _objects_edit(NULL,1)',
	'/property\?object=([^&]*) => _property(1)',
	'/reports/? => _reports_main',
	'/reports/ip\?ip=(.+) => _reports_ip(1)',
	'/reports/load/? => _reports_load',
	'/tags/? => _tags_main',
	'(/)tags/(\d+)\.html => _tags_main(NULL,2)',
	'/visibility\?act=(show|hide)&object=([^&]*) => _visibility(2)',
));
